### ISSUE TITLE
Cannot apply multitenancy/add-roles policy

### ISSUE THREAD

**Issue by patelrit** [nirmata/kyverno-policies#36]
When applying this policy, I get the error
kubectl apply -f multitenancy/add-roles.yaml
error: error validating "multitenancy/add-roles.yaml": error validating data: ValidationError(ClusterPolicy.spec.rules[0].mutate): unknown field "overlay" in io.kyverno.v1.ClusterPolicy.spec.rules.mutate; if you choose to ignore these errors, turn validation off with --validate=false

Kyverno version: 1.8.5

**Comment by patelrit** [comment]
@anusha94 was this issue fixed?

**Comment by anusha94** [comment]
> @anusha94 was this issue fixed?

Yes. I forgot to link the issue in PR. We can close this now.

**Comment by anusha94** [comment]
Closing as the linked PR is merged.
